export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_PASSWORD = "AUTH_PASSWORD";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_SENT_REQUEST = "AUTH_SENT_REQUEST";
export const AUTH_USER_DATA = "AUTH_USER_DATA";
export const AUTH_IS_LOGGED_IN = "AUTH_IS_LOGGED_IN";
